export {
  buildBestValidDeck,
  compareInstanceStrength,
  type BestValidDeckCard,
  type BestValidDeckResult,
  type OwnedDeckCard,
} from "./automaticDeck.js";
export {
  getBaseBattleHp,
  getDeckPower,
  type PoweredCard,
} from "./battleStats.js";
export {
  MAX_DECK_CARDS_PER_ELEMENT,
  MIN_DECK_CARDS_PER_ELEMENT,
  countDeckElements,
  validateDeckElementBalance,
  type DeckElementBalanceReason,
  type DeckElementBalanceResult,
  type DeckElementCard,
  type DeckElementCounts,
} from "./deckBalance.js";
export {
  BASE_POWER_BY_LEVEL,
  CARD_LEVEL_PROGRESS_REQUIRED,
  CARD_LEVEL_TABLE,
  CARD_RARITY_LEVEL_RANGES,
  MAX_CARD_LEVEL,
  MIN_CARD_LEVEL,
  advanceCardLevel,
  applyElementalPotential,
  canLevelUp,
  generateStandardBonusPower,
  getBasePowerForLevel,
  getCardLevelTableEntry,
  getCardPower,
  getElementValueForLevel,
  getRarityForLevel,
  getRarityLevelRange,
  getTransferableElementValue,
  getUpgradeGoldPrice,
  getUpgradeProgress,
  isGoldLevel,
  selectGeneratedLevelForRarity,
  selectShopLevelForRarity,
  SHOP_LEVEL_RANGES,
  type CardPowerInput,
  type CardLevelTableEntry,
  type CardProgressionState,
  type CardRarityLevelRange,
  type GeneratedLevelPolicy,
  type IntegerRandomSource,
  type UpgradeAvailability,
} from "./cardProgression.js";
export {
  applyAbsorptionEfficiency,
  getPlayerCollectionModifiers,
  type PlayerCollectionModifiers,
} from "./collectionModifiers.js";
export {
  DUEL_ACTIVE_CARD_COUNT,
  DUEL_POOL_SIZE,
  NORMAL_MATCHMAKING_RANGE_PCT,
  STREAK_MATCHMAKING_RANGE_PCT,
  WIDENED_MATCHMAKING_STREAK,
  applyAccountXp,
  applyDuelOutcomeToStats,
  calculateDuelDamage,
  calculateDuelReward,
  cycleCardPoolSlot,
  getDuelBaseSilver,
  getDuelBaseXp,
  getDuelLogVisualState,
  getEffectiveDeckPower,
  getElementMultiplier,
  getMatchmakingRange,
  getRequiredAccountXp,
  getStartingHp,
  initializeCyclicCardPool,
  isDeckPowerInMatchmakingRange,
  resolveDuelExchange,
  shuffleCards,
  type AccountXpResult,
  type ActiveCards,
  type CyclicCardPool,
  type DuelReward,
  type DuelStats,
  type MatchmakingRange,
  type RandomSource,
  type ResolvedDuelExchange,
} from "./duel.js";
