export {
  buildBestValidDeck,
  compareInstanceStrength,
  type BestValidDeckCard,
  type BestValidDeckResult,
  type OwnedDeckCard,
} from "./automaticDeck.js";
export {
  getBaseBattleHp,
  getDeckPower,
  type PoweredCard,
} from "./battleStats.js";
export {
  MAX_DECK_CARDS_PER_ELEMENT,
  MIN_DECK_CARDS_PER_ELEMENT,
  countDeckElements,
  validateDeckElementBalance,
  type DeckElementBalanceReason,
  type DeckElementBalanceResult,
  type DeckElementCard,
  type DeckElementCounts,
} from "./deckBalance.js";
export {
  BASE_POWER_BY_LEVEL,
  CARD_LEVEL_TABLE,
  CARD_RARITY_LEVEL_RANGES,
  MAX_CARD_LEVEL,
  MIN_CARD_LEVEL,
  advanceCardLevel,
  applyElementalPotential,
  canLevelUp,
  generateStandardBonusPower,
  getBasePowerForLevel,
  getCardLevelTableEntry,
  getCardPower,
  getElementValueForLevel,
  getRarityForLevel,
  getRarityLevelRange,
  getTransferableElementValue,
  getUpgradeGoldPrice,
  getUpgradeProgress,
  getRequiredProgressElements,
  isGoldLevel,
  selectGeneratedLevelForRarity,
  selectShopLevelForRarity,
  SHOP_LEVEL_RANGES,
  type CardPowerInput,
  type CardLevelTableEntry,
  type CardProgressionState,
  type CardRarityLevelRange,
  type GeneratedLevelPolicy,
  type IntegerRandomSource,
  type UpgradeAvailability,
} from "./cardProgression.js";
export {
  applyAbsorptionEfficiency,
  getPlayerCollectionModifiers,
  type PlayerCollectionModifiers,
} from "./collectionModifiers.js";
export {
  ACCOUNT_XP_REQUIRED_BY_LEVEL,
  DUEL_ACTIVE_CARD_COUNT,
  DUEL_POOL_SIZE,
  GUILD_CARD_APPEARANCE_CHANCE,
  MAX_ACCOUNT_LEVEL,
  NORMAL_MATCHMAKING_RANGE_PCT,
  STREAK_MATCHMAKING_RANGE_PCT,
  WIDENED_MATCHMAKING_STREAK,
  applyAccountXp,
  applyDuelOutcomeToStats,
  calculateDuelDamage,
  calculateBattleReward,
  calculateDuelReward,
  cycleCardPoolSlot,
  cycleCardPoolSlotWithGuildCard,
  getDuelBaseSilver,
  getDuelBaseXp,
  getDuelGoldReward,
  getDuelLogVisualState,
  getEffectiveDeckPower,
  getElementMultiplier,
  getMatchmakingRange,
  getRequiredAccountXp,
  getStartingHp,
  initializeCyclicCardPool,
  isDeckPowerInMatchmakingRange,
  resolveDuelExchange,
  shuffleCards,
  type AccountXpResult,
  type ActiveCards,
  type CyclicCardPool,
  type DuelReward,
  type DuelStats,
  type MatchmakingRange,
  type ModifiedBattleReward,
  type RandomSource,
  type ResolvedDuelExchange,
} from "./duel.js";
export {
  ARENA_ACTIVE_CARD_COUNT,
  ARENA_BASE_SILVER_BY_LEAGUE,
  ARENA_BOT_ACTION_INTERVAL_MS,
  ARENA_CARD_CHANGE_COSTS,
  ARENA_GOLD_DAILY_CAP,
  ARENA_GOLD_REWARDS,
  ARENA_PARTICIPANT_COUNT,
  ARENA_QUEUE_DURATION_MS,
  ARENA_RATING_CHANGES,
  ARENA_SLOT_COOLDOWN_MS,
  ARENA_SILVER_MULTIPLIERS,
  ARENA_TOKEN_REWARDS,
  calculateArenaDamage,
  compareArenaResults,
  getArenaCardChangeCost,
  getArenaMultiplier,
  getArenaRatingChange,
  getArenaReward,
} from "./arena.js";
export {
  getNextBattlePassThreshold,
  isBattlePassCircleComplete,
  isBattlePassMilestoneClaimable,
  type BattlePassThreshold,
} from "./battlePass.js";
export {
  calculateGuildRaidCurrencyReward,
  getGuildRaidCurrencyRewardPercentage,
  GUILD_RAID_BASE_GOLD_REWARD,
  GUILD_RAID_BASE_SILVER_REWARD,
  GUILD_RAID_REWARD_CARD_LEVEL_OFFSET,
} from "./guildRaid.js";
export {
  calculateEquipmentSummary,
  EQUIPMENT_ARTIFACT_SLOTS,
  EQUIPMENT_BONUS_BY_RARITY,
  EQUIPMENT_FORGE_RECIPES,
  EQUIPMENT_ELEMENT_LABELS,
  EQUIPMENT_ELEMENT_SYMBOLS,
  EQUIPMENT_RARITY_CONFIG,
  EQUIPMENT_SLOT_LABELS,
  EQUIPMENT_THING_SLOTS,
  getEquippedDefinitions,
  getEquipmentBattleModifiers,
  getEquipmentForgeRecipe,
  getEquipmentRarityBonus,
  resolveEquipmentForgeResult,
  STARTER_EQUIPMENT_DEFINITIONS,
  STARTER_PLAYER_EQUIPMENT,
  STARTER_PLAYER_EQUIPMENT_INVENTORY,
  type EquipmentArtifactBonus,
  type EquipmentArtifactSlot,
  type EquipmentBattleModifiers,
  type EquipmentForgeRecipe,
  type EquipmentSetBonus,
  type EquipmentSetId,
  type EquipmentSummary,
  type EquipmentThingSlot,
} from "./equipment.js";
export {
  EQUIPMENT_MANUAL_SOURCE_URL,
  equipmentManualHtmlToText,
  parseEquipmentManualHtml,
  parseEquipmentManualText,
  EquipmentManualParseError,
  type EquipmentManual,
  type EquipmentManualArtifactId,
  type EquipmentManualArtifactRule,
  type EquipmentManualForgeRecipe,
  type EquipmentManualLink,
  type EquipmentManualSetRule,
} from "./equipmentManual.js";
export {
  FORUM_REFERENCE_SOURCE_URL,
  GUILD_FORUM_REFERENCE_ORIGIN,
  GUILD_FORUM_REFERENCE_SOURCE_URL,
  GUILD_REFERENCE_SAMPLE_URL,
  WITCH_RAID_REFERENCE_TOPIC_URL,
  classifyReferencePageUrl,
  extractReferencePageLinks,
  parseForumIndexHtml,
  parseForumSectionHtml,
  parseForumTopicHtml,
  parseGuildAchievementsHtml,
  parseGuildForumIndexHtml,
  parseGuildForumSectionHtml,
  parseGuildForumTopicHtml,
  parseGuildMembersHtml,
  parseGuildProfileHtml,
  parseReferencePageHtml,
  referenceHtmlToText,
  type ForumCategory,
  type ForumIndexPage,
  type ForumPost,
  type ForumSectionPage,
  type ForumTopicIcon,
  type ForumTopicPage,
  type ForumTopicSummary,
  type GuildAchievementEntry,
  type GuildAchievementMode,
  type GuildAchievementsPage,
  type GuildForumIndexPage,
  type GuildForumSection,
  type GuildMember,
  type GuildMembersPage,
  type GuildProfilePage,
  type ReferenceLink,
  type ReferencePageDiscovery,
  type ReferencePageKind,
} from "./guildForumReference.js";
